export interface Country {
  iso2: string;
  name: string;
  phone: string[];
}

export const countries: Country[] = [
  { iso2: "AD", name: "Andorra", phone: ["376"] },
  { iso2: "AE", name: "United Arab Emirates", phone: ["971"] },
  { iso2: "AF", name: "Afghanistan", phone: ["93"] },
  { iso2: "AG", name: "Antigua and Barbuda", phone: ["1268"] },
  { iso2: "AI", name: "Anguilla", phone: ["1264"] },
  { iso2: "AL", name: "Albania", phone: ["355"] },
  { iso2: "AM", name: "Armenia", phone: ["374"] },
  { iso2: "AO", name: "Angola", phone: ["244"] },
  { iso2: "AQ", name: "Antarctica", phone: ["672"] },
  { iso2: "AR", name: "Argentina", phone: ["54"] },
  { iso2: "AS", name: "American Samoa", phone: ["1684"] },
  { iso2: "AT", name: "Austria", phone: ["43"] },
  { iso2: "AU", name: "Australia", phone: ["61"] },
  { iso2: "AW", name: "Aruba", phone: ["297"] },
  { iso2: "AX", name: "Aland Islands", phone: ["358"] },
  { iso2: "AZ", name: "Azerbaijan", phone: ["994"] },
  { iso2: "BA", name: "Bosnia and Herzegovina", phone: ["387"] },
  { iso2: "BB", name: "Barbados", phone: ["1246"] },
  { iso2: "BD", name: "Bangladesh", phone: ["880"] },
  { iso2: "BE", name: "Belgium", phone: ["32"] },
  { iso2: "BF", name: "Burkina Faso", phone: ["226"] },
  { iso2: "BG", name: "Bulgaria", phone: ["359"] },
  { iso2: "BH", name: "Bahrain", phone: ["973"] },
  { iso2: "BI", name: "Burundi", phone: ["257"] },
  { iso2: "BJ", name: "Benin", phone: ["229"] },
  { iso2: "BL", name: "Saint Barthelemy", phone: ["590"] },
  { iso2: "BM", name: "Bermuda", phone: ["1441"] },
  { iso2: "BN", name: "Brunei", phone: ["673"] },
  { iso2: "BO", name: "Bolivia", phone: ["591"] },
  { iso2: "BQ", name: "Bonaire, Sint Eustatius and Saba", phone: ["599"] },
  { iso2: "BR", name: "Brazil", phone: ["55"] },
  { iso2: "BS", name: "Bahamas", phone: ["1242"] },
  { iso2: "BT", name: "Bhutan", phone: ["975"] },
  { iso2: "BV", name: "Bouvet Island", phone: ["47"] },
  { iso2: "BW", name: "Botswana", phone: ["267"] },
  { iso2: "BY", name: "Belarus", phone: ["375"] },
  { iso2: "BZ", name: "Belize", phone: ["501"] },
  { iso2: "CA", name: "Canada", phone: ["1"] },
  { iso2: "CC", name: "Cocos Islands", phone: ["61"] },
  { iso2: "CD", name: "Democratic Republic of the Congo", phone: ["243"] },
  { iso2: "CF", name: "Central African Republic", phone: ["236"] },
  { iso2: "CG", name: "Republic of the Congo", phone: ["242"] },
  { iso2: "CH", name: "Switzerland", phone: ["41"] },
  { iso2: "CI", name: "Ivory Coast", phone: ["225"] },
  { iso2: "CK", name: "Cook Islands", phone: ["682"] },
  { iso2: "CL", name: "Chile", phone: ["56"] },
  { iso2: "CM", name: "Cameroon", phone: ["237"] },
  { iso2: "CN", name: "China", phone: ["86"] },
  { iso2: "CO", name: "Colombia", phone: ["57"] },
  { iso2: "CR", name: "Costa Rica", phone: ["506"] },
  { iso2: "CU", name: "Cuba", phone: ["53"] },
  { iso2: "CV", name: "Cape Verde", phone: ["238"] },
  { iso2: "CW", name: "Curacao", phone: ["599"] },
  { iso2: "CX", name: "Christmas Island", phone: ["61"] },
  { iso2: "CY", name: "Cyprus", phone: ["357"] },
  { iso2: "CZ", name: "Czech Republic", phone: ["420"] },
  { iso2: "DE", name: "Germany", phone: ["49"] },
  { iso2: "DJ", name: "Djibouti", phone: ["253"] },
  { iso2: "DK", name: "Denmark", phone: ["45"] },
  { iso2: "DM", name: "Dominica", phone: ["1767"] },
  { iso2: "DO", name: "Dominican Republic", phone: ["1"] },
  { iso2: "DZ", name: "Algeria", phone: ["213"] },
  { iso2: "EC", name: "Ecuador", phone: ["593"] },
  { iso2: "EE", name: "Estonia", phone: ["372"] },
  { iso2: "EG", name: "Egypt", phone: ["20"] },
  { iso2: "EH", name: "Western Sahara", phone: ["212"] },
  { iso2: "ER", name: "Eritrea", phone: ["291"] },
  { iso2: "ES", name: "Spain", phone: ["34"] },
  { iso2: "ET", name: "Ethiopia", phone: ["251"] },
  { iso2: "FI", name: "Finland", phone: ["358"] },
  { iso2: "FJ", name: "Fiji", phone: ["679"] },
  { iso2: "FK", name: "Falkland Islands", phone: ["500"] },
  { iso2: "FM", name: "Micronesia", phone: ["691"] },
  { iso2: "FO", name: "Faroe Islands", phone: ["298"] },
  { iso2: "FR", name: "France", phone: ["33"] },
  { iso2: "GA", name: "Gabon", phone: ["241"] },
  { iso2: "GB", name: "United Kingdom", phone: ["44"] },
  { iso2: "GD", name: "Grenada", phone: ["1473"] },
  { iso2: "GE", name: "Georgia", phone: ["995"] },
  { iso2: "GF", name: "French Guiana", phone: ["594"] },
  { iso2: "GG", name: "Guernsey", phone: ["44"] },
  { iso2: "GH", name: "Ghana", phone: ["233"] },
  { iso2: "GI", name: "Gibraltar", phone: ["350"] },
  { iso2: "GL", name: "Greenland", phone: ["299"] },
  { iso2: "GM", name: "Gambia", phone: ["220"] },
  { iso2: "GN", name: "Guinea", phone: ["224"] },
  { iso2: "GP", name: "Guadeloupe", phone: ["590"] },
  { iso2: "GQ", name: "Equatorial Guinea", phone: ["240"] },
  { iso2: "GR", name: "Greece", phone: ["30"] },
  {
    iso2: "GS",
    name: "South Georgia and the South Sandwich Islands",
    phone: ["500"],
  },
  { iso2: "GT", name: "Guatemala", phone: ["502"] },
  { iso2: "GU", name: "Guam", phone: ["1671"] },
  { iso2: "GW", name: "Guinea-Bissau", phone: ["245"] },
  { iso2: "GY", name: "Guyana", phone: ["592"] },
  { iso2: "HK", name: "Hong Kong", phone: ["852"] },
  { iso2: "HM", name: "Heard Island and McDonald Islands", phone: ["672"] },
  { iso2: "HN", name: "Honduras", phone: ["504"] },
  { iso2: "HR", name: "Croatia", phone: ["385"] },
  { iso2: "HT", name: "Haiti", phone: ["509"] },
  { iso2: "HU", name: "Hungary", phone: ["36"] },
  { iso2: "ID", name: "Indonesia", phone: ["62"] },
  { iso2: "IE", name: "Ireland", phone: ["353"] },
  { iso2: "IL", name: "Israel", phone: ["972"] },
  { iso2: "IM", name: "Isle of Man", phone: ["44"] },
  { iso2: "IN", name: "India", phone: ["91"] },
  { iso2: "IO", name: "British Indian Ocean Territory", phone: ["246"] },
  { iso2: "IQ", name: "Iraq", phone: ["964"] },
  { iso2: "IR", name: "Iran", phone: ["98"] },
  { iso2: "IS", name: "Iceland", phone: ["354"] },
  { iso2: "IT", name: "Italy", phone: ["39"] },
  { iso2: "JE", name: "Jersey", phone: ["44"] },
  { iso2: "JM", name: "Jamaica", phone: ["1876"] },
  { iso2: "JO", name: "Jordan", phone: ["962"] },
  { iso2: "JP", name: "Japan", phone: ["81"] },
  { iso2: "KE", name: "Kenya", phone: ["254"] },
  { iso2: "KG", name: "Kyrgyzstan", phone: ["996"] },
  { iso2: "KH", name: "Cambodia", phone: ["855"] },
  { iso2: "KI", name: "Kiribati", phone: ["686"] },
  { iso2: "KM", name: "Comoros", phone: ["269"] },
  { iso2: "KN", name: "Saint Kitts and Nevis", phone: ["1869"] },
  { iso2: "KP", name: "North Korea", phone: ["850"] },
  { iso2: "KR", name: "South Korea", phone: ["82"] },
  { iso2: "KW", name: "Kuwait", phone: ["965"] },
  { iso2: "KY", name: "Cayman Islands", phone: ["1345"] },
  { iso2: "KZ", name: "Kazakhstan", phone: ["7"] },
  { iso2: "LA", name: "Laos", phone: ["856"] },
  { iso2: "LB", name: "Lebanon", phone: ["961"] },
  { iso2: "LC", name: "Saint Lucia", phone: ["1758"] },
  { iso2: "LI", name: "Liechtenstein", phone: ["423"] },
  { iso2: "LK", name: "Sri Lanka", phone: ["94"] },
  { iso2: "LR", name: "Liberia", phone: ["231"] },
  { iso2: "LS", name: "Lesotho", phone: ["266"] },
  { iso2: "LT", name: "Lithuania", phone: ["370"] },
  { iso2: "LU", name: "Luxembourg", phone: ["352"] },
  { iso2: "LV", name: "Latvia", phone: ["371"] },
  { iso2: "LY", name: "Libya", phone: ["218"] },
  { iso2: "MA", name: "Morocco", phone: ["212"] },
  { iso2: "MC", name: "Monaco", phone: ["377"] },
  { iso2: "MD", name: "Moldova", phone: ["373"] },
  { iso2: "ME", name: "Montenegro", phone: ["382"] },
  { iso2: "MF", name: "Saint Martin", phone: ["590"] },
  { iso2: "MG", name: "Madagascar", phone: ["261"] },
  { iso2: "MH", name: "Marshall Islands", phone: ["692"] },
  { iso2: "MK", name: "North Macedonia", phone: ["389"] },
  { iso2: "ML", name: "Mali", phone: ["223"] },
  { iso2: "MM", name: "Myanmar", phone: ["95"] },
  { iso2: "MN", name: "Mongolia", phone: ["976"] },
  { iso2: "MO", name: "Macao", phone: ["853"] },
  { iso2: "MP", name: "Northern Mariana Islands", phone: ["1670"] },
  { iso2: "MQ", name: "Martinique", phone: ["596"] },
  { iso2: "MR", name: "Mauritania", phone: ["222"] },
  { iso2: "MS", name: "Montserrat", phone: ["1664"] },
  { iso2: "MT", name: "Malta", phone: ["356"] },
  { iso2: "MU", name: "Mauritius", phone: ["230"] },
  { iso2: "MV", name: "Maldives", phone: ["960"] },
  { iso2: "MW", name: "Malawi", phone: ["265"] },
  { iso2: "MX", name: "Mexico", phone: ["52"] },
  { iso2: "MY", name: "Malaysia", phone: ["60"] },
  { iso2: "MZ", name: "Mozambique", phone: ["258"] },
  { iso2: "NA", name: "Namibia", phone: ["264"] },
  { iso2: "NC", name: "New Caledonia", phone: ["687"] },
  { iso2: "NE", name: "Niger", phone: ["227"] },
  { iso2: "NF", name: "Norfolk Island", phone: ["672"] },
  { iso2: "NG", name: "Nigeria", phone: ["234"] },
  { iso2: "NI", name: "Nicaragua", phone: ["505"] },
  { iso2: "NL", name: "Netherlands", phone: ["31"] },
  { iso2: "NO", name: "Norway", phone: ["47"] },
  { iso2: "NP", name: "Nepal", phone: ["977"] },
  { iso2: "NR", name: "Nauru", phone: ["674"] },
  { iso2: "NU", name: "Niue", phone: ["683"] },
  { iso2: "NZ", name: "New Zealand", phone: ["64"] },
  { iso2: "OM", name: "Oman", phone: ["968"] },
  { iso2: "PA", name: "Panama", phone: ["507"] },
  { iso2: "PE", name: "Peru", phone: ["51"] },
  { iso2: "PF", name: "French Polynesia", phone: ["689"] },
  { iso2: "PG", name: "Papua New Guinea", phone: ["675"] },
  { iso2: "PH", name: "Philippines", phone: ["63"] },
  { iso2: "PK", name: "Pakistan", phone: ["92"] },
  { iso2: "PL", name: "Poland", phone: ["48"] },
  { iso2: "PM", name: "Saint Pierre and Miquelon", phone: ["508"] },
  { iso2: "PN", name: "Pitcairn", phone: ["64"] },
  { iso2: "PR", name: "Puerto Rico", phone: ["1"] },
  { iso2: "PS", name: "Palestine", phone: ["970"] },
  { iso2: "PT", name: "Portugal", phone: ["351"] },
  { iso2: "PW", name: "Palau", phone: ["680"] },
  { iso2: "PY", name: "Paraguay", phone: ["595"] },
  { iso2: "QA", name: "Qatar", phone: ["974"] },
  { iso2: "RE", name: "Reunion", phone: ["262"] },
  { iso2: "RO", name: "Romania", phone: ["40"] },
  { iso2: "RS", name: "Serbia", phone: ["381"] },
  { iso2: "RU", name: "Russia", phone: ["7"] },
  { iso2: "RW", name: "Rwanda", phone: ["250"] },
  { iso2: "SA", name: "Saudi Arabia", phone: ["966"] },
  { iso2: "SB", name: "Solomon Islands", phone: ["677"] },
  { iso2: "SC", name: "Seychelles", phone: ["248"] },
  { iso2: "SD", name: "Sudan", phone: ["249"] },
  { iso2: "SE", name: "Sweden", phone: ["46"] },
  { iso2: "SG", name: "Singapore", phone: ["65"] },
  { iso2: "SH", name: "Saint Helena", phone: ["290"] },
  { iso2: "SI", name: "Slovenia", phone: ["386"] },
  { iso2: "SJ", name: "Svalbard and Jan Mayen", phone: ["47"] },
  { iso2: "SK", name: "Slovakia", phone: ["421"] },
  { iso2: "SL", name: "Sierra Leone", phone: ["232"] },
  { iso2: "SM", name: "San Marino", phone: ["378"] },
  { iso2: "SN", name: "Senegal", phone: ["221"] },
  { iso2: "SO", name: "Somalia", phone: ["252"] },
  { iso2: "SR", name: "Suriname", phone: ["597"] },
  { iso2: "SS", name: "South Sudan", phone: ["211"] },
  { iso2: "ST", name: "Sao Tome and Principe", phone: ["239"] },
  { iso2: "SV", name: "El Salvador", phone: ["503"] },
  { iso2: "SX", name: "Sint Maarten", phone: ["1721"] },
  { iso2: "SY", name: "Syria", phone: ["963"] },
  { iso2: "SZ", name: "Eswatini", phone: ["268"] },
  { iso2: "TC", name: "Turks and Caicos Islands", phone: ["1649"] },
  { iso2: "TD", name: "Chad", phone: ["235"] },
  { iso2: "TF", name: "French Southern Territories", phone: ["262"] },
  { iso2: "TG", name: "Togo", phone: ["228"] },
  { iso2: "TH", name: "Thailand", phone: ["66"] },
  { iso2: "TJ", name: "Tajikistan", phone: ["992"] },
  { iso2: "TK", name: "Tokelau", phone: ["690"] },
  { iso2: "TL", name: "East Timor", phone: ["670"] },
  { iso2: "TM", name: "Turkmenistan", phone: ["993"] },
  { iso2: "TN", name: "Tunisia", phone: ["216"] },
  { iso2: "TO", name: "Tonga", phone: ["676"] },
  { iso2: "TR", name: "Turkey", phone: ["90"] },
  { iso2: "TT", name: "Trinidad and Tobago", phone: ["1868"] },
  { iso2: "TV", name: "Tuvalu", phone: ["688"] },
  { iso2: "TW", name: "Taiwan", phone: ["886"] },
  { iso2: "TZ", name: "Tanzania", phone: ["255"] },
  { iso2: "UA", name: "Ukraine", phone: ["380"] },
  { iso2: "UG", name: "Uganda", phone: ["256"] },
  { iso2: "UM", name: "United States Minor Outlying Islands", phone: ["1"] },
  { iso2: "US", name: "United States", phone: ["1"] },
  { iso2: "UY", name: "Uruguay", phone: ["598"] },
  { iso2: "UZ", name: "Uzbekistan", phone: ["998"] },
  { iso2: "VA", name: "Vatican", phone: ["39"] },
  { iso2: "VC", name: "Saint Vincent and the Grenadines", phone: ["1784"] },
  { iso2: "VE", name: "Venezuela", phone: ["58"] },
  { iso2: "VG", name: "British Virgin Islands", phone: ["1284"] },
  { iso2: "VI", name: "U.S. Virgin Islands", phone: ["1340"] },
  { iso2: "VN", name: "Vietnam", phone: ["84"] },
  { iso2: "VU", name: "Vanuatu", phone: ["678"] },
  { iso2: "WF", name: "Wallis and Futuna", phone: ["681"] },
  { iso2: "WS", name: "Samoa", phone: ["685"] },
  { iso2: "YE", name: "Yemen", phone: ["967"] },
  { iso2: "YT", name: "Mayotte", phone: ["262"] },
  { iso2: "ZA", name: "South Africa", phone: ["27"] },
  { iso2: "ZM", name: "Zambia", phone: ["260"] },
  { iso2: "ZW", name: "Zimbabwe", phone: ["263"] },
];

// Arabic country names mapping
export const arabicCountryNames: Record<string, string> = {
  AD: "أندورا",
  AE: "الإمارات العربية المتحدة",
  AF: "أفغانستان",
  AG: "أنتيغوا وبربودا",
  AI: "أنغيلا",
  AL: "ألبانيا",
  AM: "أرمينيا",
  AO: "أنغولا",
  AQ: "القارة القطبية الجنوبية",
  AR: "الأرجنتين",
  AS: "ساموا الأمريكية",
  AT: "النمسا",
  AU: "أستراليا",
  AW: "أروبا",
  AX: "جزر آلاند",
  AZ: "أذربيجان",
  BA: "البوسنة والهرسك",
  BB: "بربادوس",
  BD: "بنغلاديش",
  BE: "بلجيكا",
  BF: "بوركينا فاسو",
  BG: "بلغاريا",
  BH: "البحرين",
  BI: "بوروندي",
  BJ: "بنين",
  BL: "سان بارتيليمي",
  BM: "برمودا",
  BN: "بروناي",
  BO: "بوليفيا",
  BQ: "بونير وسينت أوستاتيوس وسابا",
  BR: "البرازيل",
  BS: "الباهاما",
  BT: "بوتان",
  BV: "جزيرة بوفيت",
  BW: "بوتسوانا",
  BY: "بيلاروسيا",
  BZ: "بليز",
  CA: "كندا",
  CC: "جزر كوكوس",
  CD: "جمهورية الكونغو الديمقراطية",
  CF: "جمهورية أفريقيا الوسطى",
  CG: "الكونغو",
  CH: "سويسرا",
  CI: "ساحل العاج",
  CK: "جزر كوك",
  CL: "تشيلي",
  CM: "الكاميرون",
  CN: "الصين",
  CO: "كولومبيا",
  CR: "كوستاريكا",
  CU: "كوبا",
  CV: "الرأس الأخضر",
  CW: "كوراساو",
  CX: "جزيرة الكريسماس",
  CY: "قبرص",
  CZ: "التشيك",
  DE: "ألمانيا",
  DJ: "جيبوتي",
  DK: "الدنمارك",
  DM: "دومينيكا",
  DO: "جمهورية الدومينيكان",
  DZ: "الجزائر",
  EC: "الإكوادور",
  EE: "إستونيا",
  EG: "مصر",
  EH: "الصحراء الغربية",
  ER: "إريتريا",
  ES: "إسبانيا",
  ET: "إثيوبيا",
  FI: "فنلندا",
  FJ: "فيجي",
  FK: "جزر فوكلاند",
  FM: "ميكرونيسيا",
  FO: "جزر فارو",
  FR: "فرنسا",
  GA: "الغابون",
  GB: "المملكة المتحدة",
  GD: "غرينادا",
  GE: "جورجيا",
  GF: "غويانا الفرنسية",
  GG: "غيرنسي",
  GH: "غانا",
  GI: "جبل طارق",
  GL: "جرينلاند",
  GM: "غامبيا",
  GN: "غينيا",
  GP: "غوادلوب",
  GQ: "غينيا الاستوائية",
  GR: "اليونان",
  GS: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
  GT: "غواتيمالا",
  GU: "غوام",
  GW: "غينيا بيساو",
  GY: "غويانا",
  HK: "هونغ كونغ",
  HM: "جزيرة هيرد وجزر ماكدونالد",
  HN: "هندوراس",
  HR: "كرواتيا",
  HT: "هايتي",
  HU: "المجر",
  ID: "إندونيسيا",
  IE: "أيرلندا",
  IL: "إسرائيل",
  IM: "جزيرة مان",
  IN: "الهند",
  IO: "إقليم المحيط الهندي البريطاني",
  IQ: "العراق",
  IR: "إيران",
  IS: "آيسلندا",
  IT: "إيطاليا",
  JE: "جيرسي",
  JM: "جامايكا",
  JO: "الأردن",
  JP: "اليابان",
  KE: "كينيا",
  KG: "قيرغيزستان",
  KH: "كمبوديا",
  KI: "كيريباتي",
  KM: "جزر القمر",
  KN: "سانت كيتس ونيفيس",
  KP: "كوريا الشمالية",
  KR: "كوريا الجنوبية",
  KW: "الكويت",
  KY: "جزر كايمان",
  KZ: "كازاخستان",
  LA: "لاوس",
  LB: "لبنان",
  LC: "سانت لوسيا",
  LI: "ليختنشتاين",
  LK: "سريلانكا",
  LR: "ليبيريا",
  LS: "ليسوتو",
  LT: "ليتوانيا",
  LU: "لوكسمبورغ",
  LV: "لاتفيا",
  LY: "ليبيا",
  MA: "المغرب",
  MC: "موناكو",
  MD: "مولدوفا",
  ME: "الجبل الأسود",
  MF: "سان مارتن",
  MG: "مدغشقر",
  MH: "جزر مارشال",
  MK: "مقدونيا الشمالية",
  ML: "مالي",
  MM: "ميانمار",
  MN: "منغوليا",
  MO: "ماكاو",
  MP: "جزر ماريانا الشمالية",
  MQ: "مارتينيك",
  MR: "موريتانيا",
  MS: "مونتسرات",
  MT: "مالطا",
  MU: "موريشيوس",
  MV: "المالديف",
  MW: "ملاوي",
  MX: "المكسيك",
  MY: "ماليزيا",
  MZ: "موزمبيق",
  NA: "ناميبيا",
  NC: "كاليدونيا الجديدة",
  NE: "النيجر",
  NF: "جزيرة نورفولك",
  NG: "نيجيريا",
  NI: "نيكاراغوا",
  NL: "هولندا",
  NO: "النرويج",
  NP: "نيبال",
  NR: "ناورو",
  NU: "نيوي",
  NZ: "نيوزيلندا",
  OM: "عمان",
  PA: "بنما",
  PE: "بيرو",
  PF: "بولينيسيا الفرنسية",
  PG: "بابوا غينيا الجديدة",
  PH: "الفلبين",
  PK: "باكستان",
  PL: "بولندا",
  PM: "سان بيير وميكلون",
  PN: "جزر بيتكايرن",
  PR: "بورتوريكو",
  PS: "فلسطين",
  PT: "البرتغال",
  PW: "بالاو",
  PY: "باراغواي",
  QA: "قطر",
  RE: "ريونيون",
  RO: "رومانيا",
  RS: "صربيا",
  RU: "روسيا",
  RW: "رواندا",
  SA: "المملكة العربية السعودية",
  SB: "جزر سليمان",
  SC: "سيشيل",
  SD: "السودان",
  SE: "السويد",
  SG: "سنغافورة",
  SH: "سانت هيلينا وأسينشين وتريستان دا كونها",
  SI: "سلوفينيا",
  SJ: "سفالبارد وجان ماين",
  SK: "سلوفاكيا",
  SL: "سيراليون",
  SM: "سان مارينو",
  SN: "السنغال",
  SO: "الصومال",
  SR: "سورينام",
  SS: "جنوب السودان",
  ST: "ساو تومي وبرينسيبي",
  SV: "السلفادور",
  SX: "سينت مارتن",
  SY: "سوريا",
  SZ: "إسواتيني",
  TC: "جزر توركس وكايكوس",
  TD: "تشاد",
  TF: "الأقاليم الجنوبية الفرنسية",
  TG: "توغو",
  TH: "تايلاند",
  TJ: "طاجيكستان",
  TK: "توكيلاو",
  TL: "تيمور الشرقية",
  TM: "تركمانستان",
  TN: "تونس",
  TO: "تونغا",
  TR: "تركيا",
  TT: "ترينيداد وتوباغو",
  TV: "توفالو",
  TW: "تايوان",
  TZ: "تنزانيا",
  UA: "أوكرانيا",
  UG: "أوغندا",
  UM: "جزر الولايات المتحدة النائية الصغرى",
  US: "الولايات المتحدة",
  UY: "الأوروغواي",
  UZ: "أوزبكستان",
  VA: "الفاتيكان",
  VC: "سانت فنسنت والغرينادين",
  VE: "فنزويلا",
  VG: "جزر فيرجن البريطانية",
  VI: "جزر فيرجن الأمريكية",
  VN: "فيتنام",
  VU: "فانواتو",
  WF: "واليس وفوتونا",
  WS: "ساموا",
  YE: "اليمن",
  YT: "مايوت",
  ZA: "جنوب أفريقيا",
  ZM: "زامبيا",
  ZW: "زيمبابوي",
};

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find((country) => country.phone[0] === code);
};

export const getCountryByIso2 = (iso2: string): Country | undefined => {
  return countries.find((country) => country.iso2 === iso2);
};
